services:
  webgoat:
    image: webgoat/webgoat
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 3000:8080

  modsecurity:
    build:
      context: modsecurity
    ports:
      - 8080:8080
    volumes:
      - ./attacker/log:/var/log/modsec/
    environment:
      - BACKEND=http://webgoat:8080
      - PORT=8080
      - MODSEC_RULE_ENGINE=DetectionOnly
      - MODSEC_AUDIT_LOG_PARTS=ABIJDEFHZ
      - MODSEC_AUDIT_LOG=/var/log/modsec/audit.log
  attacker:
    build:
      context: attacker
    tty: true
