services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/users?sslmode=disable

  modsecurity:
    build:
      context: modsecurity
    ports:
      - 8080:8080
    volumes:
      - ./modsecurity/log:/var/log/modsec/
    environment:
      - BACKEND=http://app
      - PORT=8080
      # - MODSEC_RULE_ENGINE=DetectionOnly
      - MODSEC_AUDIT_LOG_PARTS=ABIJDEFHZ
      - MODSEC_AUDIT_LOG=/var/log/modsec/audit.log

volumes:
  postgres_data:
